<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Guru;

class GuruSeeder extends Seeder
{
    public function run(): void
    {
        $guru = [
            [
                'nama' => 'Jajang Ridwan, S.T.',
                'nip' => null,
                'jabatan' => 'Guru Teknik Otomotif',
                'mapel' => 'Teknik Otomotif',
                'kategori' => 'guru',
                'foto' => 'jajang-ridwan.jpg',
            ],
            [
                'nama' => 'Yani Cahyani, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Bahasa Inggris',
                'mapel' => 'Bahasa Inggris',
                'kategori' => 'guru',
                'foto' => 'yani-cahyani.jpg',
            ],
            [
                'nama' => 'Mega Nurunnisa, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Bahasa Indonesia dan Seni Budaya',
                'mapel' => 'Bahasa Indonesia & Seni Budaya',
                'kategori' => 'guru',
                'foto' => 'mega-nurunnisa.jpg',
            ],
            [
                'nama' => 'Mia Rusmiati, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Matematika dan Bahasa Inggris',
                'mapel' => 'Matematika & Bahasa Inggris',
                'kategori' => 'guru',
                'foto' => 'mia-rusmiati.jpg',
            ],
            [
                'nama' => 'Silvi Danu Respita, S.T.',
                'nip' => null,
                'jabatan' => 'Guru PPLG',
                'mapel' => 'PPLG',
                'kategori' => 'guru',
                'foto' => 'silvi-danu-respita.jpg',
            ],
            [
                'nama' => 'Siti Rahmawati, S.E.',
                'nip' => null,
                'jabatan' => 'Guru PAI.BP',
                'mapel' => 'PAI.BP',
                'kategori' => 'guru',
                'foto' => 'siti-rahmawati.jpg',
            ],
            [
                'nama' => 'Ai Nurhasanah, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Matematika dan Informatika',
                'mapel' => 'Matematika & Informatika',
                'kategori' => 'guru',
                'foto' => 'ai-nurhasanah.jpg',
            ],
            [
                'nama' => 'Isnan Wiranursyeha, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Bahasa Indonesia',
                'mapel' => 'Bahasa Indonesia',
                'kategori' => 'guru',
                'foto' => 'isnan-wiranursyeha.jpg',
            ],
            [
                'nama' => 'Rina Susana, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru PPLG',
                'mapel' => 'PPLG',
                'kategori' => 'guru',
                'foto' => 'rina-susana.jpg',
            ],
            [
                'nama' => 'Nurdiansah, S.IP.',
                'nip' => '198612022025211077',
                'jabatan' => 'ADM Persuratan, Kesiswaan dan Kurikulum',
                'mapel' => 'Administrasi',
                'kategori' => 'staf',
                'foto' => 'nurdiansah.jpg',
            ],
            [
                'nama' => 'Sima Kristina, S.Kom.',
                'nip' => '200109132025212035',
                'jabatan' => 'ADM Keuangan dan Publikasi',
                'mapel' => 'Administrasi',
                'kategori' => 'staf',
                'foto' => 'sima-kristina.jpg',
            ],
            [
                'nama' => 'Sakti Alamsyah, S.E.',
                'nip' => '197410012025211033',
                'jabatan' => 'Administrasi Sarpras',
                'mapel' => 'Administrasi',
                'kategori' => 'staf',
                'foto' => 'sakti-alamsyah.jpg',
            ],
            [
                'nama' => 'Ayi Suryati, A.MA.Pust.',
                'nip' => '197707112025212035',
                'jabatan' => 'Administrasi Perpustakaan',
                'mapel' => 'Administrasi Perpustakaan',
                'kategori' => 'staf',
                'foto' => 'ayi-suryati.jpg',
            ],
            [
                'nama' => 'Nurah Alwaini, A.MA.Pust.',
                'nip' => '199202092025212081',
                'jabatan' => 'Administrasi Perpustakaan',
                'mapel' => 'Administrasi Perpustakaan',
                'kategori' => 'staf',
                'foto' => 'nurah-alwaini.jpg',
            ],
            [
                'nama' => 'Ramdan Bastaman',
                'nip' => '199308132025211163',
                'jabatan' => 'Administrasi Sarpras',
                'mapel' => 'Administrasi',
                'kategori' => 'staf',
                'foto' => 'ramdan-bastaman.jpg',
            ],
            [
                'nama' => 'Saripul Basar',
                'nip' => '197009152025211041',
                'jabatan' => 'Laboran APHP',
                'mapel' => 'Laboran APHP',
                'kategori' => 'staf',
                'foto' => 'saripul-basar.jpg',
            ],
            [
                'nama' => 'Asep Purnama',
                'nip' => '198007052025211160',
                'jabatan' => 'Laboran Teknik Otomotif',
                'mapel' => 'Teknik Otomotif',
                'kategori' => 'staf',
                'foto' => 'asep-purnama.jpg',
            ],
            [
                'nama' => 'Santi Mustika',
                'nip' => '199410102025212222',
                'jabatan' => 'Laboran Pemasaran',
                'mapel' => 'Pemasaran',
                'kategori' => 'staf',
                'foto' => 'santi-mustika.jpg',
            ],
            [
                'nama' => 'Moch Najib',
                'nip' => null,
                'jabatan' => 'Laboran PPLG',
                'mapel' => 'PPLG',
                'kategori' => 'staf',
                'foto' => 'moch-najib.jpg',
            ],
            [
                'nama' => 'Ahmad Suhendra',
                'nip' => '197012072025211031',
                'jabatan' => 'Petugas Kebersihan dan Keindahan Sekolah',
                'mapel' => 'Kebersihan & Keindahan Sekolah',
                'kategori' => 'staf',
                'foto' => 'ahmad-suhendra.jpg',
            ],
            [
                'nama' => 'D Jamaludin',
                'nip' => '197502072025211040',
                'jabatan' => 'Petugas Kebersihan dan Keindahan Sekolah',
                'mapel' => 'Kebersihan & Keindahan Sekolah',
                'kategori' => 'staf',
                'foto' => 'd-jamaludin.jpg',
            ],
            [
                'nama' => 'Apendi',
                'nip' => null,
                'jabatan' => 'Petugas Kebersihan dan Keindahan Sekolah',
                'mapel' => 'Kebersihan & Keindahan Sekolah',
                'kategori' => 'staf',
                'foto' => 'apendi.jpg',
            ],
            [
                'nama' => 'Tatang Rustandi',
                'nip' => '199003182025211136',
                'jabatan' => 'Petugas Kebersihan dan Keindahan Sekolah',
                'mapel' => 'Kebersihan & Keindahan Sekolah',
                'kategori' => 'staf',
                'foto' => 'tatang-rustandi.jpg',
            ],
            [
                'nama' => 'Muldiansah',
                'nip' => '199708012025211054',
                'jabatan' => 'Petugas Keamanan dan Ketertiban Sekolah',
                'mapel' => 'Keamanan & Ketertiban Sekolah',
                'kategori' => 'staf',
                'foto' => 'muldiansah.jpg',
            ],
            [
                'nama' => 'Yogi Saputra',
                'nip' => null,
                'jabatan' => 'Petugas Keamanan dan Ketertiban Sekolah',
                'mapel' => 'Keamanan & Ketertiban Sekolah',
                'kategori' => 'staf',
                'foto' => 'yogi-saputra.jpg',
            ],
            [
                'nama' => 'Nuraeni, S.Pd.',
                'nip' => '198912032022212012',
                'jabatan' => 'Guru Matematika',
                'mapel' => 'Matematika',
                'kategori' => 'guru',
                'foto' => 'nuraeni.jpg',
            ],
            [
                'nama' => 'Ela Haryati, S.Pd.',
                'nip' => '197506052023212003',
                'jabatan' => 'Guru Pendidikan Pancasila dan PPKn',
                'mapel' => 'Pendidikan Pancasila & PPKn',
                'kategori' => 'guru',
                'foto' => 'ela-haryati.jpg',
            ],
            [
                'nama' => 'Habib Suhandar, S.Pd.',
                'nip' => '198106042023211007',
                'jabatan' => 'Guru Pendidikan Pancasila dan Sejarah',
                'mapel' => 'Pendidikan Pancasila & Sejarah',
                'kategori' => 'guru',
                'foto' => 'habib-suhandar.jpg',
            ],
            [
                'nama' => 'Nopi Yanti, S.Pd.',
                'nip' => '198811302023212010',
                'jabatan' => 'Guru Pendidikan Pancasila dan Sejarah',
                'mapel' => 'Pendidikan Pancasila & Sejarah',
                'kategori' => 'guru',
                'foto' => 'nopi-yanti.jpg',
            ],
            [
                'nama' => 'Jaya Nur Setiawandi, S.Pd.',
                'nip' => '198711192024211002',
                'jabatan' => 'Guru PJOK dan Bahasa Sunda',
                'mapel' => 'PJOK & Bahasa Sunda',
                'kategori' => 'guru',
                'foto' => 'jaya-nur-setiawandi.jpg',
            ],
            [
                'nama' => 'Setiawan, S.E.',
                'nip' => '198602112025211005',
                'jabatan' => 'Guru Pemasaran',
                'mapel' => 'Pemasaran',
                'kategori' => 'guru',
                'foto' => 'setiawan.jpg',
            ],
            [
                'nama' => 'Dini Andriani, S.E.',
                'nip' => '199012022025212004',
                'jabatan' => 'Guru Pemasaran',
                'mapel' => 'Pemasaran',
                'kategori' => 'guru',
                'foto' => 'dini-andriani.jpg',
            ],
            [
                'nama' => 'Emi Resmiyati, S.Pd.',
                'nip' => '199107042025212010',
                'jabatan' => 'Guru Projek Ilmu Pengetahuan Alam dan Sosial',
                'mapel' => 'Projek Ilmu Pengetahuan Alam dan Sosial',
                'kategori' => 'guru',
                'foto' => 'emi-resmiyati.jpg',
            ],
            [
                'nama' => 'Rina Susana, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Bahasa Inggris',
                'mapel' => 'Bahasa Inggris',
                'kategori' => 'guru',
                'foto' => 'rina-susana-2.jpg',
            ],
            [
                'nama' => 'Asep Muhlis Sulaeman, S.Pd.I.',
                'nip' => null,
                'jabatan' => 'Guru PAI.BP',
                'mapel' => 'PAI.BP',
                'kategori' => 'guru',
                'foto' => 'asep-muhlis-sulaeman.jpg',
            ],
            [
                'nama' => 'Yayup Hindriyani, S.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Matematika dan Informatika',
                'mapel' => 'Matematika & Informatika',
                'kategori' => 'guru',
                'foto' => 'yayup-hindriyani.jpg',
            ],
            [
                'nama' => 'Wahyudin, S.Tr.Kom.',
                'nip' => null,
                'jabatan' => 'Guru PPLG',
                'mapel' => 'PPLG',
                'kategori' => 'guru',
                'foto' => 'wahyudin.jpg',
            ],
            [
                'nama' => 'Kamalia, S.E.',
                'nip' => null,
                'jabatan' => 'Guru Pemasaran',
                'mapel' => 'Pemasaran',
                'kategori' => 'guru',
                'foto' => 'kamalia.jpg',
            ],
            [
                'nama' => 'Andri Muhuir, S.T.',
                'nip' => null,
                'jabatan' => 'Guru Teknik Otomotif',
                'mapel' => 'Teknik Otomotif',
                'kategori' => 'guru',
                'foto' => 'andri-muhuir.jpg',
            ],
            [
                'nama' => 'Moch. Yoga Agung N., S.Pd., M.Pd.',
                'nip' => null,
                'jabatan' => 'Guru Bahasa Sunda',
                'mapel' => 'Bahasa Sunda',
                'kategori' => 'guru',
                'foto' => 'moch-yoga-agung.jpg',
            ],
            [
                'nama' => 'Rahmat Setiawan, S.T.',
                'nip' => null,
                'jabatan' => 'Guru PPLG',
                'mapel' => 'PPLG',
                'kategori' => 'guru',
                'foto' => 'rahmat-setiawan.jpg',
            ],
            [
                'nama' => 'Ende Iskandar, S.TP.',
                'nip' => null,
                'jabatan' => 'Guru APHP',
                'mapel' => 'APHP',
                'kategori' => 'guru',
                'foto' => 'ende-iskandar.jpg',
            ],
            [
                'nama' => 'Didi Mei Somatri, S.Kom.',
                'nip' => null,
                'jabatan' => 'Guru PPLG',
                'mapel' => 'PPLG',
                'kategori' => 'guru',
                'foto' => 'didi-mei-somatri.jpg',
            ],
            [
                'nama' => 'Budiana Hermawan, S.TP.',
                'nip' => '197303012021211002',
                'jabatan' => 'Guru APHP',
                'mapel' => 'APHP',
                'kategori' => 'guru',
                'foto' => 'budiana-hermawan.jpg',
            ],
            [
                'nama' => 'Edeh Kurniasih, S.Pd.',
                'nip' => '197604032021212003',
                'jabatan' => 'Guru Bahasa Indonesia',
                'mapel' => 'Bahasa Indonesia',
                'kategori' => 'guru',
                'foto' => 'edeh-kurniasih.jpg',
            ],
            [
                'nama' => 'Romi Darmayadi, S.Pd., S.T.',
                'nip' => '198005242021211003',
                'jabatan' => 'Guru Teknik Otomotif',
                'mapel' => 'Teknik Otomotif',
                'kategori' => 'guru',
                'foto' => 'romi-darmayadi.jpg',
            ],
            [
                'nama' => 'Eli Maryamah, S.Pd.',
                'nip' => '197301152022212001',
                'jabatan' => 'Guru Pemasaran',
                'mapel' => 'Pemasaran',
                'kategori' => 'guru',
                'foto' => 'eli-maryamah.jpg',
            ],
            [
                'nama' => 'Nanang Suryana, S.E., M.M.',
                'nip' => '197909252022211004',
                'jabatan' => 'Guru Pemasaran',
                'mapel' => 'Pemasaran',
                'kategori' => 'guru',
                'foto' => 'nanang-suryana.jpg',
            ],
            [
                'nama' => 'Indra Priatna, S.Pd.',
                'nip' => '198403292022211005',
                'jabatan' => 'Guru Pendidikan Pancasila dan Informatika',
                'mapel' => 'Pendidikan Pancasila & Informatika',
                'kategori' => 'guru',
                'foto' => 'indra-priatna.jpg',
            ],
            [
                'nama' => 'Indra Murgianto, S.Pd.',
                'nip' => '198403302022211010',
                'jabatan' => 'Guru Pemasaran',
                'mapel' => 'Pemasaran',
                'kategori' => 'guru',
                'foto' => 'indra-murgianto.jpg',
            ],
            [
                'nama' => 'Dedi Sukardi, S.Pd.',
                'nip' => '198910032022211009',
                'jabatan' => 'Guru PJOK',
                'mapel' => 'PJOK',
                'kategori' => 'guru',
                'foto' => 'dedi-sukardi.jpg',
            ],
        ];

        foreach ($guru as $data) {
            Guru::create($data);
        }
    }
}